[package]
name = "eth-archive"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1.18.0", features = ["full"] }
parquet = "9.0.0"
datafusion = "7.1.0"
thiserror = "1.0.31"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
futures = "0.3.21"
crossbeam = "0.8.1"

[dependencies.web3]
version = "0.18.0"
default-features = false
features = ["http-rustls-tls"]
