[package]
name = "eth-archive"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1.18.0", features = ["full"] }
datafusion = "7.1.0"

[dependencies.arrow2]
version = "0.11.2"
features = [ "io_parquet" ]

[dependencies.parquet2]
version = "0.12"
default_features = false
features = [ "snappy" ]
