[package]
name = "eth-archive"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1.18.0", features = ["full"] }
serde_json = "1.0.79"
serde = { version = "1.0", features = ["derive"] }
parquet = "9.0.0"
parquet_derive = "9.0.0"
datafusion = "7.1.0"

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["json", "rustls-tls", "gzip"]
