[package]
name = "eth-archive"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1.18.0", features = ["full"] }

[dependencies.arrow2]
version = "0.11.2"
features = [ "io_parquet", "io_parquet_compression" ]
