version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=eth-archive-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eth-archive-db
    ports:
      - 5432:5432
    volumes:
      - eth_archive_data:/var/lib/postgresql/data

volumes:
  eth_archive_data: