eth_rpc_url = "http://195.201.56.33:8545"
data_path = "data"
database_path = "db"
start_block = 10000000
end_block = 14000000

[block]
block_write_threshold = 1200000
tx_write_threshold = 3300000
batch_size = 50
concurrency = 16

[log]
log_write_threshold = 8000000
batch_size = 10
concurrency = 100

[retry]
num_tries = 3
secs_between_tries = 5
