eth_rpc_url = "http://195.201.56.33:8545"
data_path = "data"
database_path = "db"
start_block = 7000000
end_block = 11000000

[block]
block_write_threshold = 1200000
block_row_group_size = 100000000
tx_write_threshold = 3300000
tx_row_group_size = 100000000
batch_size = 50
concurrency = 100

[log]
log_write_threshold = 8000000
log_row_group_size = 100000000
batch_size = 50
concurrency = 100

[retry]
num_tries = 3
secs_between_tries = 5
