[retry]
secs_between_tries = 3

[db]
user = "postgres"
password = "12345"
dbname = "eth_archive_db"
host = "localhost"
port = 5432

[data]
target_partitions = 12
batch_size = 512
logs_path = "data/log"
blocks_path = "data/block"
transactions_path = "data/tx"
max_block_range = 1000000
default_block_range = 500000
response_log_limit = 100000
parquet_state_refresh_interval_secs = 10

[http_server]
ip = "127.0.0.1"
port = 8080
