block_window_size = 1000000
block_depth_offset = 20

[retry]
secs_between_tries = 3

[db]
user = "postgres"
password = "12345"
dbname = "eth_archive_db"
host = "localhost"
port = 5432

[ingest]
eth_rpc_url = "http://195.201.56.33:8545"
block_batch_size = 50
log_batch_size = 50
http_req_concurrency = 100
