[db]
user = "eth-archive-user"
password = "password"
dbname = "eth-archive-db"
host = "localhost"
port = 5432

[ingest]
eth_rpc_url = "http://195.201.56.33:8545"
tx_batch_size = 50
log_batch_size = 50
http_req_concurrency = 100
retry = { secs_between_tries = 3 }
from_block = 10000000