[package]
name = "eth-archive-ingester"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.5.9"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
log = "0.4"
env_logger = "0.9"
serde_json = "1"
url = { version = "2", features = ["serde"] } 
futures = "0.3"
mimalloc = { version = "*", default-features = false }
clap = { version = "3", features = ["derive"] }

eth-archive-core = { path = "../core" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["json", "rustls-tls", "gzip"]
