[package]
name = "eth-archive-ingester"
version = "0.1.0"
edition = "2021"

[dependencies]
scylla = "0.4"
serde = { version = "1", features = ["derive"] }
toml = "0.5.9"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
log = "0.4"
env_logger = "0.9"
clap = { version = "3", features = ["derive"] }
hex = "0.4.3"

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["json", "rustls-tls", "gzip"]
