[package]
name = "eth-archive-ingester"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.5.9"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
log = "0.4"
env_logger = "0.9"
clap = { version = "3", features = ["derive"] }
serde_json = "1"
url = { version = "2", features = ["serde"] } 
futures = "0.3"
refinery = { version = "0.8", features = ["tokio-postgres"]}
tokio-postgres = { version = "0.7.6", features = [ "with-serde_json-1", "with-uuid-1" ] }

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["json", "rustls-tls", "gzip"]

[dependencies.deadpool-postgres]
version = "0.10.2"
features = [ "rt_tokio_1" ]
